### ISSUE TITLE
実行時にシミュレーション項目を選択するオプションの実装

### ISSUE THREAD

**Issue by xr0038** [JASMINE-Mission/jasmine-imagesim#49]
`ctl.json` に `effect` というエントリを追加して以下の項目を on/off できるようにする．

- ace
- wfe
- flat_interpix
- flat_intrapix
- psf
- rolling_shutter

現在 `hotfix_switch` にて大澤が作業中．

**Comment by xr0038** [comment]
`rolling_shutter` はどこで実装されていますかね？
……よくわからなかったので今回は見送ろうと思います．

**Comment by tkamizuka** [comment]
@xr0038 
これは一応解決ですかね。
rolling_shutter の効果は integrate の中で実施しています。
この効果をオフにしようと思うと…何か別の integrate を実装する必要があるかもしれません。

**Comment by xr0038** [comment]
コメントありがとうございます． rolling shutter は結構奥のほうなのですね……．

`hotfix_switches` は既に merge しているのでこの issue は close とします．
