### ISSUE TITLE
normalize_pixar の領分？

### ISSUE THREAD

**Issue by tkamizuka** [JASMINE-Mission/jasmine-imagesim#88]
@HajimeKawahara 
先日の #87 で normalize_pixar という関数が実装されましたが、その中で ace simulation が real でないときの対応である「一枚目の plate を他の plate にコピーする」という操作がなされています (下記URL部分)。ただ、この動作は normalize_pixar という関数名にそぐわない気がしました。改善案として run_simpix みたいな関数を作ってその中で simpix の実施とこの操作をさせるようにするというのはいかがでしょうか。また、normalize_pixar では magnitude に応じた「スケーリング」をしていると思いますがこういう操作も「normalize」というものなのでしょうか。どちらかというとその前の simpix の出力を割り算したりしている操作が normalize な気がしており、こちらの考え方も整理させていただけますと幸いです。
https://github.com/JASMINE-Mission/jasmine-imagesim/blob/6dcc9af90a563b22ffbc55c820e9da253c66bc42/src/jis/binutils/runpixsim.py#L185

**Comment by HajimeKawahara** [comment]
なるほど、賛成です。修正案を出してPRします
