### ISSUE TITLE
Nts_per_plate 計算のバグ

### ISSUE THREAD

**Issue by tkamizuka** [JASMINE-Mission/jasmine-imagesim#92]
@HajimeKawahara 
下記の部分ですが、
````
    Nts_per_plate = int((control_params.tplate+detector.readparams.t_scan)/
                                    control_params.ace_control['dtace']+0.5)
````
とすべきかと思います。ご確認ください。
https://github.com/JASMINE-Mission/jasmine-imagesim/blob/6dcc9af90a563b22ffbc55c820e9da253c66bc42/src/jis/binutils/runphotonsim.py#L138

**Comment by HajimeKawahara** [comment]
ありがとうございます！　#88, #89, #90, #91, #92, についてPRを出していただけないでしょうか？
よろしくお願いいたします。

**Comment by tkamizuka** [comment]
これは…上塚がやれということですね。

**Comment by tkamizuka** [comment]
お時間を見つけるお時間をいただきます。

**Comment by HajimeKawahara** [comment]
すみません、お願いします。

**Comment by tkamizuka** [comment]
@HajimeKawahara 上記の件ですが、単一のというのは #88-#92 まとめて一つの PR という意味でよろしいでしょうか。

**Comment by HajimeKawahara** [comment]
はい、そのようにしていただければと思います@tkamizuka
